name: Build Documentation

on:
  push:
    paths:
      - '.github/workflows/build-docs.yml'
      - 'docs_src/*'
      - 'docs_src/*/*'
      - 'docs_src/*/*/*'
      - 'docs_src/*/*/*/*'
      - 'cmp/*'
      - 'cmp/*/*'

jobs:
  docs-build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      run: npm i && cd docs_src && npm i && npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs_src/__DOCS__/dist/svelte-chota